# Generated by Django 4.1.6 on 2023-12-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceOrder_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("products", models.TextField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_type", models.CharField(max_length=50)),
                ("transactions_id", models.CharField(max_length=255)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
